#!/usr/bin/env bash
#
# This file is part of shamnium. Copyright (C) 2013 and above Shogun <shogun_panda@cowtech.it>.
# Licensed under the MIT license, which can be found at http://www.opensource.org/licenses/mit-license.php.
#

if [[ -n "${BASH_VERSION:-}" ]] &&
  (( 65536 * ${BASH_VERSINFO[0]} + 256 * ${BASH_VERSINFO[1]} + ${BASH_VERSINFO[2]} < 197145 ))
then
  echo "shamnium requires at least BASH 3.2.25 (you have $BASH_VERSION)."
  exit 1
fi

COMMAND="$1"
[ "$COMMAND" != "uninstall" ] && COMMAND="install"
DESTDIR=/tmp/shamnium-$(date +%Y%m%d%H%M%S)

git clone https://github.com/ShogunPanda/zishamnium -q -- "${DESTDIR}" && cd "${DESTDIR}" && sudo rake "${COMMAND}[true]" && rm -rf "${DESTDIR}"